# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81e4e461b75f0d23083313046b0c95094eadc376f670e185b39995392dc661e70ece56a8ef3562a41b88b9178edc7a51343bc311aa72ee459b1164a12094b4fd

test:
  secret_key_base: d7c314ac7aad89065d6da4d10a6e7b1444f7451240b853437eb54e74f7f572796fd07e4fd4cfb2af4c34d3e67551410b6f741dbbad382bb8971cec7681e255ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
